### ISSUE TITLE
Enable gzip on supportkit CDN

### ISSUE THREAD

**Issue by captn3m0** [supportkit/supportkit-js#58]
The current size of `supportkit.min.js` is 215kb, which will be going up once #48 is merged. Unfortunately, supportkit is the slowest and the largest JS file on our site, and your cloudfront config doesn't have gzip enabled.

Please enable gzip: http://checkgzipcompression.com/?url=https%3A%2F%2Fcdn.supportkit.io%2Fsupportkit.min.js

**Comment by lemieux** [comment]
Great idea! I'll see what I can do. That'd be a very good improvement.

Thanks!

**Comment by lemieux** [comment]
I'll reopen this, the merge closed it automatically and it is not fixed yet.

**Comment by lemieux** [comment]
This will mostly likely result in a change of CDN, which is planned for this sprint. I'll keep you posted.

**Comment by captn3m0** [comment]
I couldn't navigate the different PRs properly, so asking: is this live and available yet?

**Comment by lemieux** [comment]
hey, I was about to give you an update on that. I tried couple of things to compress the files and failed at it because Cloudfront doesn't support on-the-fly gzip, so it was being complicated for nothing. We decided to switch CDN instead and enable gzip on it. We should do that next week. I'll keep you posted.

**Comment by lemieux** [comment]
@captn3m0 deployed and enabled!

**Comment by captn3m0** [comment]
:+1: /cc @pronav
